## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

## Ans)In Python, the data type of a variable is determined dynamically based on the value assigned to it. However, it is possible to create a list and an array using different data types.
## Here is an example code to demonstrate the difference in data types between a list and an array list: In this code, we are using the NumPy library to create an array list. The type() function is used to print the data type of both variables.

In [3]:
import numpy as np
list_ = [ '1','2','3','4','5' ]
array_list = np.array(object = list_)
# Printing the data types of both variables
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


## Q2) Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [4]:
list_ = [ '1','2','3','4','5' ]
array_list = np.array(object = list_)
for ele in list_:
    print(type(ele))
for ele1 in array_list:
    print(type(ele1))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


## Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

## Ans) Yes, there will be a difference in the data type of the elements present in list_ and array_list after the following change: array_list = np.array(object = list_, dtype = int)
## This code creates a new numpy array array_list from the existing list list_, with data type as int. The dtype parameter specifies the data type of the new array, which in this case is int.To print the data types of each and every element present in both list_ and array_list, we can use the same approach as before, i.e., use a loop to iterate over each element and use the type() function to get the data type of that element. Here's an example code

In [5]:
list_ = [ '1','2','3','4','5' ]
array_list=np.array(object=list_,dtype=int)
for ele in list_:
    print(type(ele))
for ele1 in array_list:
    print(type(ele1))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


## Q4. Write a code to find the following characteristics of variable, num_array:
## (i) shape
## (ii) size

## Ans)To find the shape and size of the numpy array num_array, we can use the shape and size attributes of the array

In [6]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
# Find the shape of the array
print("Shape of num_array:", num_array.shape)

# Find the size of the array
print("Size of num_array:", num_array.size)

Shape of num_array: (2, 3)
Size of num_array: 6


## Q5) Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
## [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [8]:
import numpy as np

# Creating a 3x3 numpy array containing zeros only
zeros_array = np.zeros(shape=(3, 3))

# Printing the array
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Q6. Create an identity matrix of shape (5,5) using numpy functions?
## [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [10]:
import numpy as np

# Creating a 5x5 identity matrix
identity_matrix = np.identity(n=5)

# Printing the matrix
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
